# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('nickname', models.CharField(default='改个昵称吧', max_length=30, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='avatars', verbose_name='头像')),
                ('motto', models.CharField(default='', max_length=100, verbose_name='个性签名')),
                ('is_member', models.BooleanField(default=False, verbose_name='是否会员')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理员')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'ordering': ['-add_time'],
                'verbose_name_plural': '用户',
            },
        ),
    ]
