# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0, verbose_name='背诵单词水平 1:四级 2:六级 3:托福 4:雅思'),
        ),
        migrations.AddField(
            model_name='user',
            name='word_num_day',
            field=models.IntegerField(default=40, verbose_name='每天背诵量'),
        ),
    ]
