# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CetFourWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, unique=True, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(null=True, verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(db_index=True, default=0, verbose_name='总表对应id')),
            ],
            options={
                'verbose_name': '四级词汇',
                'db_table': 'cet4_words',
                'abstract': False,
                'verbose_name_plural': '四级词汇',
            },
        ),
        migrations.CreateModel(
            name='CetSixWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, unique=True, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(null=True, verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(db_index=True, default=0, verbose_name='总表对应id')),
            ],
            options={
                'verbose_name': '六级词汇',
                'db_table': 'cet6_words',
                'abstract': False,
                'verbose_name_plural': '六级词汇',
            },
        ),
        migrations.CreateModel(
            name='IeltsWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, unique=True, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(null=True, verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(db_index=True, default=0, verbose_name='总表对应id')),
            ],
            options={
                'verbose_name': '雅思词汇',
                'db_table': 'ielts_words',
                'abstract': False,
                'verbose_name_plural': '雅思词汇',
            },
        ),
        migrations.CreateModel(
            name='ReciteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(db_index=True, default=0, verbose_name='单词id')),
                ('level', models.IntegerField(choices=[(1, '四级'), (2, '六级'), (3, '托福'), (4, '雅思')], default=0, verbose_name='单词水平')),
                ('user_id', models.IntegerField(db_index=True, default=0, verbose_name='用户id')),
                ('status', models.IntegerField(choices=[(0, '未背'), (1, '正在背'), (2, '背完')], default=0, verbose_name='背诵状态 0:还没背,1:背诵中,2:已掌握')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '背诵记录表',
                'db_table': 'recite_record',
                'ordering': ['-update_time'],
                'verbose_name_plural': '背诵记录表',
            },
        ),
        migrations.CreateModel(
            name='SynonymGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'synonym_group',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('lx', models.TextField()),
            ],
            options={
                'db_table': 'cetsix',
            },
        ),
        migrations.CreateModel(
            name='ToeftWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, unique=True, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(null=True, verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(db_index=True, default=0, verbose_name='总表对应id')),
            ],
            options={
                'verbose_name': '托福词汇',
                'db_table': 'toeft_words',
                'abstract': False,
                'verbose_name_plural': '托福词汇',
            },
        ),
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(db_index=True, default=0, verbose_name='单词id')),
                ('user_id', models.IntegerField(db_index=True, default=0, verbose_name='用户id')),
                ('content', models.TextField(default='', verbose_name='笔记内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_share', models.BooleanField(default=False, verbose_name='笔记是否共享')),
            ],
            options={
                'verbose_name': '单词笔记',
                'db_table': 'word_note',
                'verbose_name_plural': '单词笔记',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, unique=True, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(null=True, verbose_name='例句')),
                ('synonym_id', models.IntegerField(db_index=True, default=0, verbose_name='近义词组id')),
            ],
            options={
                'verbose_name': '单词总表',
                'db_table': 'words',
                'ordering': ['word'],
                'verbose_name_plural': '单词总表',
            },
        ),
    ]
