# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CetFourWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, default='', max_length=50, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(default=0, verbose_name='总表对应id')),
            ],
            options={
                'db_table': 'cet4_words',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CetSixWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, default='', max_length=50, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(default=0, verbose_name='总表对应id')),
            ],
            options={
                'db_table': 'cet6_words',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IeltsWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, default='', max_length=50, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(default=0, verbose_name='总表对应id')),
            ],
            options={
                'db_table': 'ielts_words',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToeftWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, default='', max_length=50, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(verbose_name='例句')),
                ('is_import', models.BooleanField(default=False, verbose_name='是否重点词汇')),
                ('global_id', models.IntegerField(default=0, verbose_name='总表对应id')),
            ],
            options={
                'db_table': 'toeft_words',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, default='', max_length=50, verbose_name='单词')),
                ('meaning', models.CharField(default='', max_length=100, verbose_name='中文意思')),
                ('example', models.TextField(verbose_name='例句')),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
