# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cetfourwords',
            name='global_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='总表对应id'),
        ),
        migrations.AlterField(
            model_name='cetsixwords',
            name='global_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='总表对应id'),
        ),
        migrations.AlterField(
            model_name='ieltswords',
            name='global_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='总表对应id'),
        ),
        migrations.AlterField(
            model_name='toeftwords',
            name='global_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='总表对应id'),
        ),
    ]
