# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20161214_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(default=0, verbose_name='单词id')),
                ('level', models.IntegerField(default=0, verbose_name='单词水平')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('status', models.IntegerField(default=0, verbose_name='背诵状态 0:还没背,1:背诵中,3:已掌握')),
                ('note_id', models.IntegerField(default=0, verbose_name='笔记')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-update_time'],
                'db_table': 'reciterecord',
            },
        ),
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(default=0, verbose_name='单词id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_share', models.BooleanField(default=False, verbose_name='笔记是否共享')),
            ],
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'ordering': ['word']},
        ),
    ]
