# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20161214_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetfourwords',
            options={'verbose_name': '四级词汇'},
        ),
        migrations.AlterModelOptions(
            name='cetsixwords',
            options={'verbose_name': '六级词汇'},
        ),
        migrations.AlterModelOptions(
            name='ieltswords',
            options={'verbose_name': '雅思词汇'},
        ),
        migrations.AlterModelOptions(
            name='reciterecord',
            options={'ordering': ['-update_time'], 'verbose_name': '背诵记录表'},
        ),
        migrations.AlterModelOptions(
            name='toeftwords',
            options={'verbose_name': '托福词汇'},
        ),
        migrations.AlterModelOptions(
            name='wordnote',
            options={'verbose_name': '单词笔记'},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'ordering': ['word'], 'verbose_name': '单词总表', 'verbose_name_plural': '单词总表'},
        ),
        migrations.AddField(
            model_name='wordnote',
            name='content',
            field=models.TextField(default='', verbose_name='笔记内容'),
        ),
        migrations.AlterField(
            model_name='wordnote',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='wordnote',
            name='word_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='单词id'),
        ),
        migrations.AlterModelTable(
            name='reciterecord',
            table='recite_record',
        ),
        migrations.AlterModelTable(
            name='wordnote',
            table='wordnote',
        ),
    ]
