# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20161216_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetfourwords',
            options={'verbose_name': '四级词汇', 'verbose_name_plural': '四级词汇'},
        ),
        migrations.AlterModelOptions(
            name='cetsixwords',
            options={'verbose_name': '六级词汇', 'verbose_name_plural': '六级词汇'},
        ),
        migrations.AlterModelOptions(
            name='ieltswords',
            options={'verbose_name': '雅思词汇', 'verbose_name_plural': '雅思词汇'},
        ),
        migrations.AlterModelOptions(
            name='reciterecord',
            options={'ordering': ['-update_time'], 'verbose_name': '背诵记录表', 'verbose_name_plural': '背诵记录表'},
        ),
        migrations.AlterModelOptions(
            name='toeftwords',
            options={'verbose_name': '托福词汇', 'verbose_name_plural': '托福词汇'},
        ),
        migrations.AlterModelOptions(
            name='wordnote',
            options={'verbose_name': '单词笔记', 'verbose_name_plural': '单词笔记'},
        ),
        migrations.RemoveField(
            model_name='reciterecord',
            name='note_id',
        ),
        migrations.AlterField(
            model_name='reciterecord',
            name='level',
            field=models.IntegerField(choices=[(1, '四级'), (2, '六级'), (3, '托福'), (4, '雅思')], default=0, verbose_name='单词水平'),
        ),
        migrations.AlterField(
            model_name='reciterecord',
            name='status',
            field=models.IntegerField(choices=[(0, '未背'), (1, '正在背'), (2, '背完')], default=0, verbose_name='背诵状态 0:还没背,1:背诵中,3:已掌握'),
        ),
    ]
