# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20161216_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cetfourwords',
            name='word',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='单词'),
        ),
        migrations.AlterField(
            model_name='cetsixwords',
            name='word',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='单词'),
        ),
        migrations.AlterField(
            model_name='ieltswords',
            name='word',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='单词'),
        ),
        migrations.AlterField(
            model_name='reciterecord',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='reciterecord',
            name='word_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='单词id'),
        ),
        migrations.AlterField(
            model_name='toeftwords',
            name='word',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='单词'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='单词'),
        ),
    ]
